# Generated by Django 4.2.1 on 2023-05-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makineUstGrub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makine_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=50)),
                ('urun_aciklamasi', models.CharField(max_length=50)),
                ('urun_ust_grup_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='makineler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makine_adi', models.CharField(max_length=50)),
                ('makine_aciklamasi', models.CharField(max_length=50)),
                ('makine_ust_grup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makineler', to='mosapi.makineustgrub')),
            ],
        ),
        migrations.CreateModel(
            name='makine_icerikleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adedi', models.IntegerField()),
                ('makine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makineler', to='mosapi.makineler')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='mosapi.urunler')),
            ],
        ),
    ]
