# Generated by Django 4.2.1 on 2023-05-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makineustgrub',
            old_name='makine_adi',
            new_name='makine_Ust_Grup_adi',
        ),
    ]
