# Generated by Django 4.2.1 on 2023-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosapi', '0002_rename_makine_adi_makineustgrub_makine_ust_grup_adi'),
    ]

    operations = [
        migrations.CreateModel(
            name='urunUstGrub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_Ust_Grup_adi', models.CharField(max_length=50)),
            ],
        ),
    ]
